export const homeObjOne = {
    id: 'services',
    lightBg: true,
    lightText: false,
    lightTextDesc: false,
    topLine: '',
    headline: 'JOIN THE POOL PARTY',
    description: 'Users are currently saving a total of ~7 Bitcoin this month. Dip your feet in the pool and start saving as little as one satoshi',
    buttonLabel: 'Join',
    imgStart: true,
    img: require('../../images/swympoolparty.svg').default,
    alt: 'Graphics img',
    dark: false,
    primary: false,
    darkText: true, 
    redirectTo: 'projects',
}

export const homeObjTwo = {
    id: 'services',
    lightBg: true,
    lightText: false,
    lightTextDesc: false,
    topLine: '',
    headline: 'HAVE FUN WHILE SAVING',
    description: 'Lets be real, just holding your Bitcoin can be boring. Why not have some fun and win Bitcoin? Enjoy the upside of winning a jackpot prize simply while saving.',
    buttonLabel: 'Get started',
    imgStart: false,
    img: require('../../images/pool-swym.svg').default,
    alt: 'Cellphone Image',
    dark: false,
    primary: false,
    darkText: true, 
    redirectTo: 'projects',
}

export const homeObjThree = {
    id: 'swym',
    lightBg: true,
    lightText: false,
    lightTextDesc: false,
    topLine: '',
    headline: 'THE POOL PARTY IS JUST GETTING STARTED',
    description:'',
    // buttonLabel: 'Start!',
    imgStart: false,
    img: require('../../images/coins-swym.svg').default,
    alt: 'Email image',
    dark: true,
    primary: true,
    darkText: true, 
    // redirectTo: 'contact',
}